# Use the official Elasticsearch image as the base image
FROM elasticsearch:8.10.2

# Cannot run elastic as root user
USER elasticsearch

# Run Elasticsearch and Python script when the container starts
CMD ["/usr/share/elasticsearch/bin/elasticsearch"]
