services:
  webir_db:
    container_name: postgresql_db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  webir_pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - webir_db

  webir_backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    volumes:
      - ./src:/src
    ports:
      - 8080:8080
    depends_on:
      - webir_db
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.10.2
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  db-data:
  esdata:

